#!/bin/sh
# Build and run the CuTe measurements. No GPU, no CUDA toolkit.
set -eu

check=false
case "${1-}" in
  --check) check=true ;;
  "") ;;
  *) echo "usage: $0 [--check]" >&2; exit 2 ;;
esac

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
CUTLASS_DIR=${CUTLASS_DIR:-$HOME/refs/cutlass}
CCCL_DIR=${CCCL_DIR:-$HOME/refs/cccl}

for d in "$CUTLASS_DIR/include/cute" "$CCCL_DIR/libcudacxx/include/cuda"; do
  [ -d "$d" ] || { echo "not found: $d  (set CUTLASS_DIR / CCCL_DIR)" >&2; exit 1; }
done

echo "CUTLASS: $(git -C "$CUTLASS_DIR" log -1 --format='%h %ad' --date=short 2>/dev/null || echo '?')"
echo

out=$(mktemp -d); trap 'rm -rf "$out"' EXIT
generated="$out/cute-numbers.tex"
raw="$out/raw"
: > "$raw"
for src in "$here"/*.cpp; do
  name=$(basename "$src" .cpp)
  g++ -std=c++17 -O1 \
      -I "$here/stub" \
      -I "$CCCL_DIR/libcudacxx/include" \
      -I "$CUTLASS_DIR/include" \
      -o "$out/$name" "$src"
  "$out/$name" | tee -a "$raw"
  echo
done

# The figures the paper quotes, as \newcommands, so none is transcribed.
# Generated here rather than in paper/eval.sh because this needs CUTLASS
# and CCCL checkouts, which the rest of the build does not.
grep '^#cute ' "$raw" | awk '
function group(v,   t, r) {
  t = v ""; r = ""
  while (length(t) > 3) { r = "{,}" substr(t, length(t)-2) r; t = substr(t, 1, length(t)-3) }
  return t r
}
BEGIN {
  m["comp.satisfied"]        = "cuteCompSatisfied"
  m["comp.satisfied_broken"] = "cuteCompSatisfiedBroken"
  m["comp.violated"]         = "cuteCompViolated"
  m["comp.violated_broken"]  = "cuteCompViolatedBroken"
  m["comp.total"]            = "cuteCompTotal"
  n = split("comp.total comp.satisfied comp.satisfied_broken comp.violated comp.violated_broken", ks, " ")
}
{ s[$2] = $3 }
END {
  print "% Generated by study/run.sh against a CUTLASS checkout."
  print "% Do not edit: rerun the script instead."
  for (i = 1; i <= n; i++) printf("\\newcommand{\\%s}{%s}\n", m[ks[i]], group(s[ks[i]]))
}' > "$generated"

if $check; then
  if cmp -s "$generated" "$here/cute-numbers.tex"; then
    echo "study/cute-numbers.tex is up to date"
  else
    echo "study/cute-numbers.tex is stale; rerun study/run.sh" >&2
    diff -u "$here/cute-numbers.tex" "$generated" >&2 || true
    exit 1
  fi
else
  mv "$generated" "$here/cute-numbers.tex"
  echo "wrote study/cute-numbers.tex"
fi
